### PR TITLE
Support variable substitution in dotenv files

### PR DESCRIPTION
**Pull request by sachaos**
One of #38 .

### CODE REVIEW

**Comment by sachaos** [comment]
@joho Oh, Congratulations!
Thank you for reply.

**Comment by sp-emili-calonge** [comment]
Any update on this? It'd be very helpful for me if this was merged. Thanks for your work!

**Comment by joho** [comment]
Oh crap, this was totally a brain fart, I thought I had merged this and it was just plugging away on master. Sorry. Merging now.

**Comment by sachaos** [comment]
Thank you! 🎉

**Comment by sp-emili-calonge** [comment]
Thanks!

**Pull request merged**
