### PR TITLE
feat: add support for embedded command evaluation

### PR DESCRIPTION
**Pull request by the-wondersmith**
A slightly updated refactoring of the work done in #55, with the previously voiced concerns addressed and basic windows support added

### CODE REVIEW

**Comment by the-wondersmith** [comment]
@joho shameless self bump

**Comment by the-wondersmith** [comment]
@joho

**Comment by the-wondersmith** [comment]
@DarthPestilane @lildragonz @hairyhenderson @durandj

Gondor Calls For Aid

**Comment by durandj** [comment]
I'm probably not the best person to review this. I don't have anything to do with this library and I commented on that previous PR because at the time I had an issue with it for the service I was maintaining but it was easier to just remove this library and make everyone use Docker Compose instead.

**Comment by joho** [comment]
Hi @the-wondersmith, _love_ that you emailed in to my work's customer support team to nudge me here.

I won't be accepting this PR per https://github.com/joho/godotenv/issues/182

**Comment by the-wondersmith** [comment]
@joho

you gotta do what you gotta do

**Comment by ccoVeille** [comment]
That's a new level of stalking

**Pull request closed without merging**
